---
title: "WB1"
author: "Andre Nieri, Livio Kuze"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(readxl)

data = read_excel("Pesquisa.xlsx", range = "A1:M178")
df = as.data.frame(data)
head(df)

model = lm(salario ~ temceo, data = df)
summary(model)

salario_hat = predict(model, newdata = data.frame(temceo=10))
salario_hat

temceo_coef = coef(model)["temceo"]
model_conselho = 300 + temceo_coef * 10
model_conselho

model_valmkt = lm(salario ~ valmkt, data = df)
summary(model_valmkt)
```

1.  Interpretação:

    O intercepto nos dá um valor de 772.43 mil dólares de salário base, e o coeficiente associado à experiência nos dá um valor de 11.75 mil dólares para cada ano adicional de experiência do CEO.

2.  Usando o modelo ajustado `(intercepto=772.43, temceo=11.75)` teríamos uma remuneração de 889.89 mil dólares.

    Usando o modelo do conselho com o coeficiente ajustado anteriormente `(intercepto=300, temceo=11.75)` teríamos uma remuneração de 417.46 mil dólares.

3.  Analisando os coeficientes, o intercepto é altamente significativo `(p < 2e-16)`, mas o coeficiente para temceo `(p = 0.0577)` não tem significância ao nível de 5%, o que sugere evidência fraca de relação `salario ~ temceo`.

    Analisando o R² `(R² = 0.02043)`, podemos dizer que o modelo explica apenas cerca de 2% da variação do salário, o que indica que há outras variáveis importantes faltando no modelo. O erro residual `(rse = 583.2)` é muito alto perto do valor ajustado de 11.75, indicando muita dispersão nos dados.

    Ao tentar outros modelos de regressão simples, encontramos o modelo `salario ~ valmkt` com uma significância maior: `(intercepto=732.44, valmkt=0.03706)`, nesse caso o intercepto não faz muito sentido econômico, pois seria de uma empresa com valor de mercado zero, mas o coeficiente de valmkt indica a relação de aumento de 0.037 mil dólares para cada aumento de 1 milhão de valor de mercado da empresa, com significância alta `(p < 2e-08)`. No entanto, esse modelo ainda não explica a maior parte da variabilidade do salário, capturando cerca de 16.5% da variação total `(R² = 0.1651)`.
